version: '3'

services:
  resnet:
    build:
      context: .
      dockerfile: Dockerfile
    image: chibachann/resset:latest
    stdin_open: true
    tty: true
    command: /bin/bash
    volumes:
      - .:/app
    working_dir: /app
    deploy:
      restart_policy:
        condition: none
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

